import json

# Example list of 127 strings
strings = [
    "Ocean (feat. Jonathan Mendelsohn)",
    "Remember",
    "Rush Over Me",
    "Cold Hearted",
    "On My Way to Heaven - Seven Lions Remix",
    "Don’t Leave",
    "Sojourn",
    "Worlds Apart",
    "Start Again (feat. Fiora)",
    "Strangers",
    "Break The Silence (feat. RBBTS)",
    "Running To The Sea - Seven Lions Remix",
    "Dreamin' (feat. Fiora)",
    "Horizon",
    "Every Time (feat. So Below)",
    "Let Go (feat. Fiora) - Festival Mix",
    "Omen In The Rain - Seven Lions Remix",
    "Calling You Home (feat. RUNN)",
    "Days to Come (feat. Fiora)",
    "All Alone - Seven Lions Remix Club",
    "Pantheon",
    "The Journey",
    "Only Now (feat. Tyler Graves)",
    "After Dark (feat. Fiora)",
    "Tokyo (feat. XIRA) - Seven Lions Remix",
    "See The End",
    "First Time (feat. Dylan Matthew)",
    "Shadows",
    "The Great Divide - Seven Lions Remix",
    "Island (feat. Nevve)",
    "A Way To Say Goodbye",
    "Coming Home - Seven Lions & Ricky Mears Festival Radio Mix",
    "Miss You (feat. GG Magree)",
    "Falling Away - Festival Mix (Radio Edit)",
    "Sahara Love - Seven Lions Remix",
    "Alive (feat. Opposite the Other)",
    "Silent Skies",
    "See You Again",
    "Easy Lover (feat. Hilda)",
    "Higher Love",
    "Need Your Love (with Noah Kahan)",
    "Freesol",
    "December",
    "Someday",
    "Without You",
    "Beautiful - Seven Lions Remix",
    "Nepenthe",
    "Foolish Of Me (feat. Jonathan Mendelsohn)",
    "Old Gods",
    "Don't Wanna Fall",
    "Stop Thinking (feat. Lights)",
    "Reason For Fighting (feat. ERV ELLO)",
    "What’s Done Is Done",
    "Lose Myself",
    "The Fall",
    "Another Way (with April Bender)",
    "Where I Won't Be Found",
    "The Blood",
    "Fractals",
    "Brightest Light (feat. Dotter)",
    "Wild And Broken (feat. RBBTS)",
    "Cusp - Radio Edit",
    "Falling Fast (feat. GG Magree)",
    "Slow Dive",
    "Coming Home",
    "Call On Me (feat. Vancouver Sleep Clinic)",
    "Still With Me - Seven Lions Remix",
    "Darkness",
    "Night Rider",
    "Rush Over Me (feat. HALIENE) - Seven Lions 1999 Remix",
    "Without You My Love",
    "Over Now",
    "Between (feat. Eli Teplin)",
    "Places I Belong",
    "Creation",
    "Miss You (feat. GG Magree) - Seven Lions and Gem & Tauri Remix",
    "Cold Skin",
    "Ones I Used To Love",
    "Worlds Apart (feat. Kerli) - Seven Lions 1999 Remix",
    "The Truth",
    "Moonlight",
    "The Sirens",
    "Rescue Me",
    "She Was",
    "Beyond The Veil (feat. JT Roach)",
    "You Got to Go - Seven Lions Remix",
    "I Wanna Know",
    "Orpheus",
    "Half Of It",
    "Below Us",
    "Satellite - Seven Lions Remix",
    "Let Go (feat. Fiora)",
    "Days To Come (feat. Fiora) - Seven Lions 1999 Remix",
    "Senseless (feat. Tyler Graves)",
    "I'll Wait For You",
    "Before You (feat. Dia Frampton)",
    "Not Even Love",
    "New Sun - Original Mix",
    "Returning To You (feat. Alison May)",
    "Black Rainbow",
    "Falling Away",
    "Polarized",
    "The End",
    "Summer Of The Occult",
    "Tyven",
    "Keep It Close",
    "Never Learn (feat. Mija)",
    "Trip Up",
    "Leaving Earth",
    "Tribe - Original Mix",
    "Higher Love (feat. Paul Meany) - Seven Lions & Jason Ross 1999 Remix",
    "Steps of Deep Slumber",
    "Revolving Muse - Original Mix",
    "Lucid Dream - Original Mix",
    "Days Turn Into Nights - Seven Lions Remix feat. Michael Logen",
    "Lucy",
    "Fortress (feat. Joni Fatora) - Seven Lions Roots Mix",
    "Serpent of Old (feat. Ciscandra Nostalgia)",
    "All I Know (Seven Lions Mix)",
    "Known You Before (with Emilie Brandt)",
    "I Don't Deserve You - Seven Lions Remix",
    "Under Pressure - Original Mix",
    "Pathless Is The Way",
    "The Paradox - Seven Lions & Dimibo Remix",
    "Where Am I - Original Mix",
    "Sun Won't Rise",
    "Another Me (with Dylan Matthew)"
]


# Initialize the JSON object
json_object = {}

# Calculate the middle index
middle_index = len(strings) // 2

# Assign values relative to 1200
for i, string in enumerate(strings):
    if i < middle_index:
        json_object[string] = 1200 + (middle_index - i)
    elif i > middle_index:
        json_object[string] = 1200 - (i - middle_index)
    else:
        json_object[string] = 1200

# Convert to JSON string
json_output = json.dumps(json_object, indent=4)
print(json_output)
